module JobCategoriesHelper
  def job(id)
    category = []
    category = [{ 'id' => ['Accounting',
                           'Financial Planning',
                           'Human Resources',
                           ' Management Consulting',
                           'Other'] },
                { 'id' => ['Data Entry',
                           'Other - Admin Support',
                           'Personal/Virtual Assistance',
                           'Project Management',
                           'Transcription',
                           ' Web Research'] },
                { 'id' => ['Customer Service',
                           'Technical Support'] },
                { 'id' => ['Data Science & Analytics'] },
                { 'id' => ['Animation',
                           'Art & Illustration',
                           'Audio Production',
                           'Brand Identity & Strategy',
                           'Graphics & Design',
                           'Motion Graphics',
                           'Photography',
                           'Physical Design',
                           ' Presentations',
                           'Video Production',
                           'Voice Talent'] },

                { 'id' => ['Database Administration',
                           'ERP/CRM Software',
                           'Information Security',
                           'Network & System Administration',

                           'Other'] },
                { 'id' => ['Contract Law',
                           'Corporate Law',
                           'Intellectual Property Law',
                           'Other'] },

                { 'id' => ['Display Advertising',
                           'Email & Marketing Automation',
                           'Lead Generation',
                           'Market & Customer Research',
                           'Marketing Strategy',
                           'Other - Sales & Marketing',
                           'Public Relations',
                           'SEM - Search Engine Marketing',
                           'SEO - Search Engine Optimization',
                           'SMM - Social Media Marketing',
                           'Telemarketing & Telesales'] },
                { 'id' => [ 'Desktop Software Development',
                  'Ecommerce Development',
                  'Game Development',
                  'Mobile Development',
                  'Other - Software Development',
                  'Product Management',
                  'QA & Testing',
                  'Scripts & Utilities',
                  'Web & Mobile Design',
                  'Web Development'] },
                { 'id' => ['Content & Copywriting',
                  'Creative Writing',
                  'Editing & Proofreading',
                  'Grant Writing',
                  'Other - Writing',
                 ' Resumes & Cover Letters',
                  'Technical Writing'] }]

    category[id.to_i]
  end
end
